/**
 * Map skill playbooks → executable workflows for run_playbook.
 * Prefer frontmatter workflowId when present; this is the fallback.
 */
export const SKILL_WORKFLOW_MAP: Record<string, string> = {
  "developer-ship-checklist": "developer-ship-checklist-job",
  "seo-site-audit": "full-seo-audit",
  "page-performance": "core-web-vitals-job",
  "social-preview": "social-preview-audit-job",
  "content-quality": "content-quality-audit-job",
  "content-refresh": "content-quality-audit-job",
  "keyword-opportunity-review": "keyword-opportunity-review-job",
  "technical-seo-audit": "technical-seo-audit-job",
  "full-seo-optimization": "full-seo-optimization-job",
  "web-security-audit": "full-security-audit",
  "dns-email-security": "email-auth-security-job",
  "secrets-and-auth-hygiene": "secrets-hygiene-job",
  "auth-token-hygiene": "auth-token-hygiene-job",
  "frontend-supply-chain": "frontend-supply-chain-job",
  "seo-deploy-regression": "seo-deploy-regression-job",
  "seo-staging-diff": "seo-deploy-regression-diff-job",
  "crawl-analysis": "internal-link-architecture-job",
  "crawl-readiness": "crawl-readiness-job",
  "structured-data-audit": "structured-data-audit-job",
  "ai-overview-readiness": "ai-overview-readiness-job",
  "site-icons-audit": "site-icons-audit-job",
  "campaign-tracking-setup": "campaign-tracking-setup-job",
  "paid-ads-copy-gate": "paid-ads-copy-gate-job",
  "growth-unit-economics": "growth-unit-economics-job",
  "email-campaign-qa": "email-campaign-qa-job",
  "landing-conversion-check": "landing-conversion-check-job",
  "dev-json-pipeline": "dev-json-pipeline-job",
  "dev-auth-debug": "dev-auth-debug-job",
  "dev-format-transform": "dev-format-transform-job",
  "fix-verify-campaign-tracking-setup": "campaign-tracking-setup-job",
  "fix-verify-paid-ads-copy-gate": "paid-ads-copy-gate-job",
  "fix-verify-growth-unit-economics": "growth-unit-economics-job",
  "fix-verify-email-campaign-qa": "email-campaign-qa-job",
  "fix-verify-landing-conversion-check": "landing-conversion-check-job",
  "fix-verify-dev-json-pipeline": "dev-json-pipeline-job",
  "fix-verify-dev-auth-debug": "dev-auth-debug-job",
  "fix-verify-dev-format-transform": "dev-format-transform-job",
  "document-pipeline": "document-convert-pipeline",
  "content-ship": "content-ship-local",
  "ship-gate": "ship-gate-job",
  "pr-preview-gate": "ship-gate-job",
  "fix-verify-ship-gate": "ship-gate-job",
  "fix-verify-security-headers": "security-headers-job",
  "fix-verify-social-preview": "social-preview-audit-job",
  "fix-verify-core-web-vitals": "core-web-vitals-job",
  "fix-verify-seo-audit": "full-seo-audit",
  "fix-verify-web-security-audit": "full-security-audit",
  "fix-verify-email-auth": "email-auth-security-job",
  "fix-verify-frontend-supply-chain": "frontend-supply-chain-job",
  "fix-verify-technical-seo": "technical-seo-audit-job",
  "fix-verify-seo-deploy-regression": "seo-deploy-regression-job",
  "fix-verify-crawl-readiness": "crawl-readiness-job",
  "fix-verify-structured-data": "structured-data-audit-job",
  "fix-verify-ai-overview-readiness": "ai-overview-readiness-job",
  "fix-verify-site-icons": "site-icons-audit-job",
};

export function skillWorkflowId(skillId: string): string | undefined {
  return SKILL_WORKFLOW_MAP[skillId];
}
